### ISSUE TITLE
toml.dump doesn't seem to work

### ISSUE THREAD

**Issue by JoeyAcc** [uiri/toml#108]
I can read toml settings, and I can get it into a custom type, `TomlSettings`.
However, when I try to write it back with `toml.dump(self, "Settings.toml")` or `toml.dump(self.__dict__, "Settings.toml")`*, it just fails with this error:
````
$ python sbr-viewer.py
Traceback (most recent call last):
  File "sbr-viewer.py", line 198, in close
    SETTINGS.write()
  File "C:\Users\Joey\WebstormProjects\sbr-viewer-brw\settings.py", line 25, in write
    toml.dump(self.__dict__, SETTINGS_FILENAME)
  File "C:\Users\Joey\AppData\Local\Programs\Python\Python35-32\lib\site-packages\toml.py", line 588, in dump
    if not f.write:
AttributeError: 'str' object has no attribute 'write'

````

*`self` here is an instance of `TomlSettings` i.e. the code lives in a method of `TomlSettings`.

Any idea what's going on here, and how this can be fixed?

**Comment by JoeyAcc** [comment]
I finally found out that it really wants a file object, not a file path, which wasn't obvious to me.
