### ISSUE TITLE
Cannot load nested table

### ISSUE THREAD

**Issue by asottile** [uiri/toml#118]
### Version

1e68e881

### Input file

```toml
[a]
b = {c = {d = 'f'}}
```

### Stacktrace

```python
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/tmp/venv/local/lib/python2.7/site-packages/toml.py", line 368, in loads
    multibackslash)
  File "/tmp/venv/local/lib/python2.7/site-packages/toml.py", line 473, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/tmp/venv/local/lib/python2.7/site-packages/toml.py", line 635, in _load_value
    _load_inline_object(v, inline_object, _dict)
  File "/tmp/venv/local/lib/python2.7/site-packages/toml.py", line 393, in _load_inline_object
    candidate_groups[0] = candidate_group + "," + candidate_groups[0]
IndexError: list index out of range
```

**Comment by uiri** [comment]
Hello,

Thank you for your bug report! Sorry for the delay in writing a fix.
