### ISSUE TITLE
__repr__ isn't implemented

### ISSUE THREAD

**Issue by daegontaven** [uiri/toml#154]
```python
>>> import os
>>> import sys
>>> import toml
>>> print(sys.modules)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 286, in _module_repr
  File "<frozen importlib._bootstrap>", line 584, in _module_repr_from_spec
AttributeError: 'str' object has no attribute 'name'
>>> os.__repr__()
"<module 'os' from '/home/taven/.pyenv/versions/3.6.4/lib/python3.6/os.py'>"
>>> os.__str__()
"<module 'os' from '/home/taven/.pyenv/versions/3.6.4/lib/python3.6/os.py'>"
>>> toml.__repr__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 286, in _module_repr
  File "<frozen importlib._bootstrap>", line 584, in _module_repr_from_spec
AttributeError: 'str' object has no attribute 'name'
>>> toml.__str__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 286, in _module_repr
  File "<frozen importlib._bootstrap>", line 584, in _module_repr_from_spec
AttributeError: 'str' object has no attribute 'name'
```

This causes any package that relies on sys.modules debugging to stop working. I believe this is a very self explanatory issue.

**Comment by uiri** [comment]
Hi Vivek, thank you for your bug report!

I am unable to reproduce this issue using either python 2 or python 3. Instead, `print(sys.modules)` lists a dictionary of modules and their string representations.

Can you please provide additional information about your environment that might help identify the issue?

**Comment by jrabbit** [comment]
I can reproduce on 3.6.

**Comment by auscompgeek** [comment]
This is actually because `__spec__` is redefined.

**Comment by daegontaven** [comment]
@auscompgeek Nice catch! 

Here's the commit https://github.com/uiri/toml/commit/d31bcc796e41b0af67294d2f01f9dc600d2cae49 and it all makes sense now.

`__spec__` is a builtin and can only be set to a `ModuleSpec` object or `None`. I think for this use case case we safely rename this variable to either `spec` or removing it altogether since it's not used anywhere else. It should be noted that neither PyYAML or the built-in json parsers have something similar to spec defined.

More here: 
- https://docs.python.org/3/reference/import.html#__spec__
- https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec
