### ISSUE TITLE
Fails to parse quoted table keys that contain brackets

### ISSUE THREAD

**Issue by ottowayi** [uiri/toml#158]
```
[nested."level[0]"]
x = 0
```
 The example above raises the following exception:

```
Traceback (most recent call last):
  File "<pyshell#12>", line 1, in <module>
    toml.loads(_in)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\toml.py", line 307, in loads
    raise TomlDecodeError("Key group not on a line by itself.")
toml.TomlDecodeError: Key group not on a line by itself.
```

As far as I can tell, this is legal in the TOML specs and does not cause an issue with pytoml. toml correctly dumps the dict, but fails to load it.

**Comment by ottowayi** [comment]
Changing [this](https://github.com/uiri/toml/blob/169cb0b920ee9ff420e8377c8eecc219c6f3abe8/toml/decoder.py#L341) line to `rsplit` instead of `split` worked for me.
