### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ProgVal** [uiri/toml#167]
I don't know very well how TOML works, but I just stumbled upon this, and it looks like an issue:

```
>>> toml.loads('foo = [ { bar="\\"{{baz}}\\""} ]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev-py/.local/lib/python3.5/site-packages/toml.py", line 373, in loads
    multibackslash)
  File "/home/dev-py/.local/lib/python3.5/site-packages/toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/home/dev-py/.local/lib/python3.5/site-packages/toml.py", line 635, in _load_value
    return (_load_array(v, _dict), "array")
  File "/home/dev-py/.local/lib/python3.5/site-packages/toml.py", line 739, in _load_array
    nval, ntype = _load_value(a[i], _dict)
  File "/home/dev-py/.local/lib/python3.5/site-packages/toml.py", line 638, in _load_value
    _load_inline_object(v, inline_object, _dict)
  File "/home/dev-py/.local/lib/python3.5/site-packages/toml.py", line 398, in _load_inline_object
    candidate_groups[0] = candidate_group + "," + candidate_groups[0]
IndexError: list index out of range
```

**Comment by uiri** [comment]
Thank you for reporting this issue! It looks like there wasn't any backslash detection for detecting string boundaries inside inline tables in arrays of inline tables. This should be fixed by the related commits.
