### ISSUE TITLE
Can't parse multiline

### ISSUE THREAD

**Issue by simplesteph** [uiri/toml#237]
The issue is with the `'` character I believe, but it can't fix it on my end. Ensure how this is buggy? The parser seems to have issues separating the two `q1` and `q2`

```
import toml

toml.loads('''
[q1]
Explanation = """
co "foo"
"He's" 
"""

[q2]
Explanation = """
co- "Lambda 's"
"""
''')
```

fails with error:
```
Traceback (most recent call last):
  File "/Users/stephanemaarek/.pyenv/versions/3.6.5/lib/python3.6/site-packages/toml/decoder.py", line 340, in loads
    value, vtype = decoder.load_value(multilinestr)
  File "/Users/stephanemaarek/.pyenv/versions/3.6.5/lib/python3.6/site-packages/toml/decoder.py", line 772, in load_value
    raise ValueError("Stuff after closed string. WTF?")
ValueError: Stuff after closed string. WTF?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephanemaarek/projects/gitlab/udemy-automation-python/practice_exams/test.py", line 14, in <module>
    ''')
  File "/Users/stephanemaarek/.pyenv/versions/3.6.5/lib/python3.6/site-packages/toml/decoder.py", line 342, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Stuff after closed string. WTF? (line 11 column 1 char 85)
```

**Comment by simplesteph** [comment]
Note that if it's replaced by  (removed `co "foo"`), then we fall under the case of https://github.com/uiri/toml/issues/230

```
import toml

toml.loads('''
[q1]
Explanation = """
"He's" 
"""

[q2]
Explanation = """
co- "Lambda 's"
"""
''')
```

**Comment by epheien** [comment]
This toml library is buggy, use tomlkit instead.

**Comment by simplesteph** [comment]
Agreed https://github.com/sdispater/tomlkit
