### ISSUE TITLE
Incorrect handling of backslashes in dict keys

### ISSUE THREAD

**Issue by AlexMedia** [uiri/toml#280]
Using toml 0.10.0 installed via pip, I run into some issues when dealing with dictionaries with backslashes in the keys. 

I've used this snippet of code to create the initial TOML file:
```python
import toml

obj = {'a\\': {'key': 'value'}}
with open("target.toml", "w") as f:
    toml.dump(obj, f)
```

Which produces the following TOML file:
```toml
["a\"]
key = "value"
```

When I try to read the file again, using the following snippet of Python...
```python
import toml
with open("target.toml", "r") as r:
    toml.load(r)
```

I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 301, in loads
    raise TomlDecodeError("Unbalanced quotes", original, i)
toml.decoder.TomlDecodeError: Unbalanced quotes (line 1 column 7 char 6)
``` 

According to the TOML spec, the issue is that the backslash in the key ("a\") has not been escaped properly when the TOML file was written. This in turn causes the decoder to treat the quote character following the backslash as part of the value and not as the end of the name.

If I manually escape the backslash in the TOML file, a second issue pops up when reading the file:
```python
import toml
with open("target.toml", "r") as r:
    obj = toml.load(r)

for k in obj.keys():
    print(k)
```

This leads to the following output being printed:
`a\\`

As you can see, the double backslash in the TOML file has been treated as two separate characters. This should have been considered as a single backslash.

**Comment by dmerejkowsky** [comment]
Got hit by the same bug. If you're looking for an alternative, you mak want to take a look at https://pypi.org/project/tomlkit/

**Comment by cur33** [comment]
@dmerejkowsky I got hit by this too; I was going to workaround it, but I see that tomlkit is style-preserving, which I was also about to work around using toml. If tomlkit is stable enough, that will likely save me a lot of time. Thanks for the recommendation!
