### ISSUE TITLE
Broken parsing of quoted strings starting with dot

### ISSUE THREAD

**Issue by spapanik** [uiri/toml#287]
Adding a key that starts with a dot breaks the parser (even when the key is quoted). Parsing works fine when the dot is in any other position.

```python
>>> import toml
>>> toml.loads("""
... ["filename.bashrc"]
... build = true
... """)
{'filename.bashrc': {'build': True}}

>>> toml.loads("""
... [".bashrc"]
... build = true
... """)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stephanos/.local/share/virtualenvs/yamk/lib/python3.8/site-packages/toml/decoder.py", line 399, in loads
    raise TomlDecodeError("Invalid group name '" +
toml.decoder.TomlDecodeError: Invalid group name 'bashrc"'. Try quoting it. (line 2 column 1 char 1)
```

**Comment by mosteo** [comment]
I've probably hit the same issue with constructs like:
```
[some.table.'...']
# contents
```

The reported error is `toml.decoder.TomlDecodeError: Invalid group name ''. Try quoting it.`. So it seems the key is considered empty.

This works fine though:
```
[some.table]
'...' = "whatever"
```
