### ISSUE TITLE
Error on dumping tables nested 4+ deep

### ISSUE THREAD

**Issue by Edward-Knight** [uiri/toml#295]
This only affects the latest version (`0.10.1`) and is fine in previous versions.

Example file that will cause the error (taken from the [toml-lang/toml](https://github.com/toml-lang/toml) readme):
```
# [x] you
# [x.y] don't
# [x.y.z] need these
[x.y.z.w] # for this to work

[x] # defining a super-table afterward is ok
```
The fourth line here (`[x.y.z.w]`) will cause the new `ValueError: Circular reference detected` exception in `toml.dumps`.

Example:

With version `0.10.0`:
```
>>> import toml
>>> import io
>>> toml.dump({'x': {'y': {'z': {'w': {}}}}}, io.StringIO())
'[x.y.z.w]\n'
>>> 
```

With version `0.10.1`:
```
>>> import toml
>>> import io
>>> toml.dump({'x': {'y': {'z': {'w': {}}}}}, io.StringIO())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../toml/encoder.py", line 29, in dump
    d = dumps(o, encoder=encoder)
  File ".../toml/encoder.py", line 67, in dumps
    raise ValueError("Circular reference detected")
ValueError: Circular reference detected
>>> 
```

**Comment by andreoliwa** [comment]
I had a similar problem.
I thought it was an issue with `OrderedDict` and dots (`.`) on TOML keys.
But the weird thing is: it works for some cases and fails on very specific cases.

Check this gist: [toml raises "ValueError: Circular reference detected" on some specific root keys](https://gist.github.com/andreoliwa/24b046dd29765b92478c8bd8ea17e16d).

For some reason, the `id()` function is returning the same value for different dict/OrderedDict objects: https://github.com/uiri/toml/blob/9c9d4beb2b7747ef80bf3a374bb1a4c0d60bfc30/toml/encoder.py#L62-L67

**Comment by ottowayi** [comment]
I'm seeing the same issue on Python 3.7 and 3.8. I'm using regulars ``dicts`` and just started getting the circular reference error after updating to 0.10.1.  I think it has to do with ``id`` returning the same value for different objects somehow?  What's even weirder is I added some tracking by using a dict of  ``{id(section) : section}`` then the issue goes away and I can't replicate it the error.

**Comment by uiri** [comment]
This appears to be a bug in the fix for #217 , which was introduced between 0.10.0 and 0.10.1

**Comment by misho88** [comment]
I'm running into the same issue. I've been working around it, but it would be nice to have a fix.

To that end, I would like to suggest using `gc.get_referents()` instead of trying to use `id()` which definitely behaves weirdly on `{}`, `[]` and others. Garbage collection with dependency cycles is why the `gc` module exists, so it should be safe to assume the implementation of `get_referents()` is reliable.

Illustrative example:

```
from gc import get_referents

def has_cycle(obj, visited=()):
    if obj in visited:
        return True
    return any(
        has_cycle(ref, visited + (obj,))
        for ref in get_referents(obj)
    )

d = { '1': { '2': { '3': { '4': {} } } } }
print(d, has_cycle(d))  # {'1': {'2': {'3': {'4': {}}}}} False
try:
    import toml
    toml.dumps(d)
except ValueError as e:
    print('false cycle detected:', e)  # false cycle detected: Circular reference detected
d['1']['2']['3']['4'] = d
print(d, has_cycle(d))  # {'1': {'2': {'3': {'4': {...}}}}} True
```

**Comment by lijunzh** [comment]
> I'm seeing the same issue on Python 3.7 and 3.8. I'm using regulars `dicts` and just started getting the circular reference error after updating to 0.10.1. I think it has to do with `id` returning the same value for different objects somehow? What's even weirder is I added some tracking by using a dict of `{id(section) : section}` then the issue goes away and I can't replicate it the error.

I can confirm this issue too. I also added a dictionary that contains the pair of `{id(secion): section}` and the issue goes away. Below is my workaround in `toml/encoder.py`. Notice that I didn't even use the `dict` I build. I simply constructed it.

```python
def dumps(o, encoder=None):
    """Stringifies input dict as toml

    Args:
        o: Object to dump into toml
        encoder: The ``TomlEncoder`` to use for constructing the output string

    Returns:
        String containing the toml corresponding to dict

    Examples:
        ```python
        >>> import toml
        >>> output = {
        ... 'a': "I'm a string",
        ... 'b': ["I'm", "a", "list"],
        ... 'c': 2400
        ... }
        >>> toml.dumps(output)
        'a = "I\'m a string"\nb = [ "I\'m", "a", "list",]\nc = 2400\n'
        ```
    """

    retval = ""
    d = {}
    if encoder is None:
        encoder = TomlEncoder(o.__class__)
    addtoretval, sections = encoder.dump_sections(o, "")
    retval += addtoretval
    outer_objs = [id(o)]
    while sections:
        section_ids = [id(section) for section in sections]
        for section in sections:
            d.updaet({id(secion): section})
        for outer_obj in outer_objs:
            if outer_obj in section_ids:
                raise ValueError("Circular reference detected")
        outer_objs += section_ids
        newsections = encoder.get_empty_table()
        for section in sections:
            addtoretval, addtosections = encoder.dump_sections(
                sections[section], section)

            if addtoretval or (not addtoretval and not addtosections):
                if retval and retval[-2:] != "\n\n":
                    retval += "\n"
                retval += "[" + section + "]\n"
                if addtoretval:
                    retval += addtoretval
            for s in addtosections:
                newsections[section + "." + s] = addtosections[s]
        sections = newsections
    return retval

```

**Comment by dirkphilip** [comment]
I didn't see this issue yet, but I was running into the same problem and created a pull request that 
should fix this issue as lijunzh mentioned. For my project, it would also be great if it could be merged and deployed soon.

**Comment by kwint** [comment]
Hi @uiri, we encounter this issue quite a bit in our setup, and we are therefore pinned to 0.10.0. But now that other dependencies (like black) are requiring toml 0.10.1 this is starting to hold us back a bit. 

Do you have time to make a new release of toml in the near future?
