### ISSUE TITLE
dumps fails with: html.unescape('&#160;Non breaking space')

### ISSUE THREAD

**Issue by scott91e1** [uiri/toml#355]
This test case:

```python
import html, toml
text = html.unescape('&#160;Non breaking space')
tags = {}
tags['text'] = text
print(toml.dumps(tags))
```

Results in this error:

    Traceback (most recent call last):
      File "toml-0.py", line 5, in <module>
        print(toml.dumps(tags))
      File "C:\py37\lib\site-packages\toml\encoder.py", line 60, in dumps
        addtoretval, sections = encoder.dump_sections(o, "")
      File "C:\py37\lib\site-packages\toml\encoder.py", line 226, in dump_sections
        unicode(self.dump_value(o[section])) + '\n')
      File "C:\py37\lib\site-packages\toml\encoder.py", line 180, in dump_value
        return dump_fn(v) if dump_fn is not None else self.dump_funcs[str](v)
      File "C:\py37\lib\site-packages\toml\encoder.py", line 113, in _dump_str
        v = [v[0] + joiner + v[1]] + v[2:]
    IndexError: list index out of range

**Comment by dargueta** [comment]
Confirmed on 0.10.2 for the following character codes: 7F-A0, AD:

```
>>> failed = []
>>> for code in range(32, 0x1ffff):
...     try:
...         toml.dumps({"text":chr(code)})
...     except IndexError:
...         failed.append(code)
>>> failed
[127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 173]
```
