### ISSUE TITLE
Comments without a parent throw an Exception

### ISSUE THREAD

**Issue by amunchet** [uiri/toml#371]
Example TOML:
```
# Start of TOML file - invalid comment
[[test]]
    round = true
```

The error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/toml/decoder.py", line 374, in loads
    decoder.embed_comments(idx, currentlevel)
  File "/usr/local/lib/python3.8/dist-packages/toml/decoder.py", line 1056, in embed_comments
    currentlevel[key] = CommentValue(currentlevel[key], comment, beginline,
KeyError: ''
```

I will open a PR to fix.

**Comment by eksortso** [comment]
Which version of the `toml` library are you using? I have CPython 3.9.4 and toml 0.10.2, and your TOML example loads without errors on my system.

**Comment by amunchet** [comment]
My case deals specifically with comments - include `decoder=toml.TomlPreserveCommentDecoder()` to receive the error.  I edited my issue to clarify.

**Comment by wimax-grapl** [comment]
(can confirm as well, with the PreserveComment enco/decoder)

**Comment by pedohorse** [comment]
would also very much appreciate if the issue gets resolved soon (considering there seem already to be a PR pending)
