### ISSUE TITLE
Wrong `An implicitly defined table can't be an array` error with array of tables syntax

### ISSUE THREAD

**Issue by NikolausDemmel** [uiri/toml#374]
I believe this TOML file, which validates fine on https://www.toml-lint.com/, wrongly causes a parse error.

```
[foo.bar]
[[baz.foo]]
[[baz.foo]]
```

With the latest release I get:

```
>>> print(yaml.dump(toml.loads("""
... [foo.bar]
... [[baz.foo]]
... [[baz.foo]]
... """)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/demmeln/.local/lib/python3.8/site-packages/toml/decoder.py", line 471, in loads
    raise TomlDecodeError("An implicitly defined "
toml.decoder.TomlDecodeError: An implicitly defined table can't be an array (line 4 column 1 char 23)
```

These variations parse correctly:

```
>>> print(yaml.dump(toml.loads("""
... [[baz.foo]]
... [[baz.foo]]
... """)))
baz:
  foo:
  - {}
  - {}
```

```
>>> print(yaml.dump(toml.loads("""
... [foo2.bar]
... [[baz.foo]]
... [[baz.foo]]
... """)))
baz:
  foo:
  - {}
  - {}
foo2:
  bar: {}

```

**Comment by Greg-Hawkridge** [comment]
Adding to this, the issue is related to the implicit use of `foo` in `[foo.bar]` and then reuse of the same key literal in `[[baz.foo]]`.

When the decoder encounters `foo` in `[foo.bar]` [here](https://github.com/uiri/toml/blob/3f637dba5f68db63d4b30967fedda51c82459471/toml/decoder.py#L466) a key error is raised and `'foo'` is added to `implicitgroups`. 

When it hits the second `[[baz.foo]]` the second part of the key matches with the `'foo'` in `implicitgroups` from the original `[foo.bar]` and it raises the error.

I don't understand the code or spec sufficiently to know if this is intended or how to correct it. But hopefully this helps diagnose the issue

In the mean time, as a **workaround** if you declare `[foo]` in advance, then it never makes it onto the `implicitgroups` list and then no error is thrown. i.e.:
```
>>> print(yaml.dump(toml.loads("""
... [foo]
... [foo.bar]
... [[baz.foo]]
... [[baz.foo]]
... """)))
baz:
  foo:
  - {}
  - {}
foo:
  bar: {}
```
