### ISSUE TITLE
Tests fail with Burn

### ISSUE THREAD

**Issue by Jenselme** [uiri/toml#39]
I tried to launch your test suite but I get some failures:

```
Test: datetime-malformed-no-z (invalid)

Expected an error, but no error was reported.
-------------------------------------------------------------------------------
Test: key-special-chars (valid)

Traceback (most recent call last):
  File "/tmp/toml-test/toml_test3.py", line 9, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/usr/lib/python3.4/site-packages/toml.py", line 72, in loads
    raise Exception("Found invalid character in key name: '#'")
Exception: Found invalid character in key name: '#'

-------------------------------------------------------------------------------
Test: key-with-pound (valid)

Traceback (most recent call last):
  File "/tmp/toml-test/toml_test3.py", line 9, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/usr/lib/python3.4/site-packages/toml.py", line 72, in loads
    raise Exception("Found invalid character in key name: '#'")
Exception: Found invalid character in key name: '#'

-------------------------------------------------------------------------------
Test: string-escapes (valid)

Traceback (most recent call last):
  File "/tmp/toml-test/toml_test3.py", line 9, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/usr/lib/python3.4/site-packages/toml.py", line 300, in loads
    value, vtype = load_value(pair[1])
  File "/usr/lib/python3.4/site-packages/toml.py", line 402, in load_value
    raise Exception("Reserved escape sequence used")
Exception: Reserved escape sequence used


59 passed, 4 failed
```

Command used: `PATH="$PATH:$(pwd)/toml_test3.py" toml-test $(pwd)/toml_test3.py` (same problems with `toml_test.py`.

I used version 0.2.0 of toml-test suite and the lastest from master with version 0.9.0 of your software. If I use the lastest version of your test suite, I get more failures:

```
Test: datetime-malformed-no-z (invalid)

Expected an error, but no error was reported.
-------------------------------------------------------------------------------
Test: key-space (invalid)

Expected an error, but no error was reported.
-------------------------------------------------------------------------------
Test: table-whitespace (invalid)

Expected an error, but no error was reported.
-------------------------------------------------------------------------------
Test: table-with-pound (invalid)

Expected an error, but no error was reported.
-------------------------------------------------------------------------------
Test: key-space (valid)

Could not find key 'a b' in parser output.
-------------------------------------------------------------------------------
Test: key-special-chars (valid)

Could not find key '~!@$^&*()_+-`1234567890[]|/?><.,;:'' in parser output.
-------------------------------------------------------------------------------
Test: table-whitespace (valid)

Could not find key 'valid key' in parser output.
-------------------------------------------------------------------------------
Test: table-with-pound (valid)

Could not find key 'key#group' in parser output.
-------------------------------------------------------------------------------
Test: unicode-escape (valid)

Traceback (most recent call last):
  File "/tmp/toml-test/toml_test.py", line 53, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/usr/lib/python2.7/site-packages/toml.py", line 300, in loads
    value, vtype = load_value(pair[1])
  File "/usr/lib/python2.7/site-packages/toml.py", line 402, in load_value
    raise Exception("Reserved escape sequence used")
Exception: Reserved escape sequence used


69 passed, 9 failed
```

Did I do something wrong? According to http://j.xqz.ca/toml-status, all tests succeeds.

**Comment by uiri** [comment]
Bug fixes for all of those except for datetime-malformed-no-z are in the tip of master. I felt that datetime-malformed-no-z is too strict in terms of what it accepts as a valid date. Last I checked, the status of datetimes in the toml spec was in flux, I'll check again and make a 0.9.1 release soon.

**Comment by uiri** [comment]
I have released 0.9.1.
It intentionally fails datetime-malformed-no-z pending toml-lang/toml#297
Let me know if there are any other problems.

**Comment by Jenselme** [comment]
Just launched tests with toml-test 0.2.0 on top of master (which currently corresponds to the 0.9.1 release) and I still have 6 tests failing on both python2 and python3:
```
▶ toml-test $(pwd)/toml_test.py                          
Test: datetime-malformed-no-z (invalid)

Expected an error, but no error was reported.
-------------------------------------------------------------------------------
Test: key-special-chars (valid)

Traceback (most recent call last):
  File "/tmp/toml/toml_test.py", line 53, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/tmp/toml/toml.py", line 91, in loads
    raise Exception("Found invalid character in key name: '"+sl[i]+"'. Try quoting the key name.")
Exception: Found invalid character in key name: '!'. Try quoting the key name.

-------------------------------------------------------------------------------
Test: key-with-pound (valid)

Traceback (most recent call last):
  File "/tmp/toml/toml_test.py", line 53, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/tmp/toml/toml.py", line 91, in loads
    raise Exception("Found invalid character in key name: '"+sl[i]+"'. Try quoting the key name.")
Exception: Found invalid character in key name: '#'. Try quoting the key name.

-------------------------------------------------------------------------------
Test: string-escapes (valid)

Traceback (most recent call last):
  File "/tmp/toml/toml_test.py", line 53, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/tmp/toml/toml.py", line 331, in loads
    value, vtype = load_value(pair[1])
  File "/tmp/toml/toml.py", line 431, in load_value
    raise Exception("Reserved escape sequence used")
Exception: Reserved escape sequence used

-------------------------------------------------------------------------------
Test: table-whitespace (valid)

Traceback (most recent call last):
  File "/tmp/toml/toml_test.py", line 53, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/tmp/toml/toml.py", line 243, in loads
    raise Exception("Invalid group name '"+groups[i]+"'. Try quoting it.")
Exception: Invalid group name 'valid key'. Try quoting it.

-------------------------------------------------------------------------------
Test: table-with-pound (valid)

Traceback (most recent call last):
  File "/tmp/toml/toml_test.py", line 53, in <module>
    tdata = toml.loads(sys.stdin.read())
  File "/tmp/toml/toml.py", line 243, in loads
    raise Exception("Invalid group name '"+groups[i]+"'. Try quoting it.")
Exception: Invalid group name 'key#group'. Try quoting it.


57 passed, 6 failed
```

Any idea what the problem migth be?

**Comment by uiri** [comment]
Sorry for the delay in responding.
The version of the test suite from the tip of master is different from test suite version 0.2.0. Test suite 0.2.0 doesn't properly quote keys per the updated spec. This leads to tests failing. The new versions of the tests which use quoted keys pass properly.

**Comment by Jenselme** [comment]
No problem. If I use toml-test from master, I only get: `Test: datetime-malformed-no-z (invalid)`. Did you have time to recheck the status of datetime? I will ask for a new release of toml-test to the maintainer.

**Comment by uiri** [comment]
Still waiting on resolution of toml-lang/toml#263

**Comment by flying-sheep** [comment]
@uiri those are long merged

**Comment by uiri** [comment]
BurntSushi/toml-test#41 removes the last failing test from the test suite.
