### ISSUE TITLE
Multi-line literal strings parsing error

### ISSUE THREAD

**Issue by foolioo** [uiri/toml#398]
toml fails for some multi-line literal strings. for example,

```shell
>>> import toml
>>> toml.loads("""foo = '''[']["]'''""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/foo/.venv/lib/python3.9/site-packages/toml/decoder.py", line 362, in loads
    raise TomlDecodeError("Unterminated string found."
toml.decoder.TomlDecodeError: Unterminated string found. Reached end of file. (line 1 column 19 char 18)
```

other toml tools has no issue handling this case. for example,
```shell
$ cat <<EOM | yq -r
foo = '''[']["]'''
EOM
foo = '''[']["]'''
```

**Comment by cpontvieux-systra** [comment]
This is the same bug as #387
