### ISSUE TITLE
Array of multi-line string literals broken

### ISSUE THREAD

**Issue by gregn610** [uiri/toml#76]
I think this is valid TOML but it breaks when parsed in python. 

    [section_heading]
    pass05  = '''func('arg1', var1)'''
    pass10  = [ '''alice''', '''bob''', '''func('arg1')''' ]
    fails01 = [ '''alice''', '''bob''', '''func('arg1', var1)''' ]
    
It does pass the go tomlv validator...

    tomlv -types tests/test_array_multiline.toml
    section_heading              Hash
        section_heading.pass05   String
        section_heading.pass10   Array
        section_heading.fails01  Array

Here's the run. It appears to be parsing the contents of the multi-line literal, but only when it's inside an array.

    Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44)
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import toml
    >>> with open('tests/test_array_multiline.toml') as tf:
    ...     toml.load(tf)
    ...
    Traceback (most recent call last):
      File "<stdin>", line 2, in <module>
      File "/Users/gregn/Projects/Software/pgldap/venv/lib/python3.5/site-packages/toml.py", line 50, in load
        return loads(f.read(), _dict)
      File "/Users/gregn/Projects/Software/pgldap/venv/lib/python3.5/site-packages/toml.py", line 286, in loads
        ret = _load_line(line, currentlevel, multikey, multibackslash)
      File "/Users/gregn/Projects/Software/pgldap/venv/lib/python3.5/site-packages/toml.py", line 353, in _load_line
        value, vtype = _load_value(pair[1])
      File "/Users/gregn/Projects/Software/pgldap/venv/lib/python3.5/site-packages/toml.py", line 490, in _load_value
        return (_load_array(v), "array")
      File "/Users/gregn/Projects/Software/pgldap/venv/lib/python3.5/site-packages/toml.py", line 577, in _load_array
        nval, ntype = _load_value(a[i])
      File "/Users/gregn/Projects/Software/pgldap/venv/lib/python3.5/site-packages/toml.py", line 512, in _load_value
        v = int(v)
    ValueError: invalid literal for int() with base 10: "var1)'''"

**Comment by uiri** [comment]
Thank you for the bug report.

I actually found two bugs: one, I forgot to include ' as a string opener; two, I forgot to consider multiline strings.

The fix will be included in the next release.
