### ISSUE TITLE
Empty inline tables fail to parse

### ISSUE THREAD

**Issue by mottosso** [uiri/toml#98]
Unsure of whether it's a problem with this parser or the spec, but found [this issue](https://github.com/BinaryMuse/toml-node/issues/24) from the Node.js world.

This:

```toml
a = { }
```

fails with

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\modules\python-toml\toml.py", line 79, in load
    return loads(f.read(), _dict)
  File "C:\modules\python-toml\toml.py", line 330, in loads
    ret = _load_line(line, currentlevel, _dict, multikey, multibackslash)
  File "C:\modules\python-toml\toml.py", line 422, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "C:\modules\python-toml\toml.py", line 572, in _load_value
    _load_inline_object(v, inline_object, _dict)
  File "C:\modules\python-toml\toml.py", line 340, in _load_inline_object
    _, value = candidate_group.split('=', 1)
ValueError: need more than 1 value to unpack
```

**Comment by mottosso** [comment]
Thanks!
